<pad> : 0
<unk> : 1
B-appliance : 2
B-cleanobject : 3
B-cookware : 4
B-foodtype : 5
B-infocode : 6
B-onofffeature : 7
B-parttype : 8
B-purposefeature : 9
B-removeobject : 10
B-replaceobject : 11
B-setfeature : 12
B-usefeature : 13
B-onoff : 14
I-cleanobject : 15
I-cookware : 16
I-foodtype : 17
I-onofffeature : 18
I-parttype : 19
I-purposefeature : 20
I-replaceobject : 21
I-setfeature : 22
I-usefeature : 23
O : 24
