<pad> : 0
<unk> : 1
B-appliance : 2
B-cleanobject : 3
B-cookware : 4
B-foodtype : 5
B-infocode : 6
B-onofffeature : 7
B-parttype : 8
B-purposefeature : 9
B-removeobject : 10
B-replaceobject : 11
B-setfeature : 12
B-usefeature : 13
I-cleanobject : 14
I-cookware : 15
I-foodtype : 16
I-onofffeature : 17
I-parttype : 18
I-purposefeature : 19
I-replaceobject : 20
I-setfeature : 21
I-usefeature : 22
O : 23
