<pad> : 0
<unk> : 1
<s> : 2
</s> : 3
B-appliance : 4
B-cleanobject : 5
B-cookware : 6
B-foodtype : 7
B-infocode : 8
B-onofffeature : 9
B-parttype : 10
B-purposefeature : 11
B-removeobject : 12
B-replaceobject : 13
B-setfeature : 14
B-usefeature : 15
I-cleanobject : 16
I-cookware : 17
I-foodtype : 18
I-onofffeature : 19
I-parttype : 20
I-purposefeature : 21
I-replaceobject : 22
I-setfeature : 23
I-usefeature : 24
O : 25
